### ISSUE TITLE
iron mongo hanging at "connecting to"

### ISSUE THREAD

**Issue by seangrogg** [iron-meteor/iron-cli#136]
Currently trying to use "$iron mongo" to access a collection; I appear to be hanging at "connecting to: 127.0.0.1/meteor". When I run the application through meteor itself, using "$meteor mongo" the collection connects just fine.

**Comment by chrisbutler** [comment]
noticed this also

**Comment by shails** [comment]
I am having the same issue with iron mongo command  hangs on 
```connecting to: 127.0.0.1:3001/meteor
```

**Comment by mitzip** [comment]
Confirmed OSX 10.10, Meteor 1.1.0.2, Iron 1.1.2

**Comment by therinken** [comment]
No connection to mongo, yet. Same issue... just hangs without resolve. Earlier had many issues with zsh, $PATH and various permission problems... perhaps there are further issues on my side that are causing the hangup??? However, I get no errors, just a frozen process. 
> [osx-10.10.3/node-0.12.1/zsh-5.0.5/meteor-1.1.0.2/iron-1.1.2]

**Comment by jasonshark** [comment]
same issue. any update?

**Comment by devatotech** [comment]
+1 same issue here.  If you `cd app` then `meteor mongo` it connects ok.

**Comment by jLouzado** [comment]
`meteor mongo` gives error message:
> mongo: You're not in a Meteor project directory.

**Comment by chrisbutler** [comment]
@mitzip any ideas for how to fix this?

**Comment by josephdburdick** [comment]
This might be a crazy idea but should there be a way to just pass the normal command into the .meteor child directory if the command is not found in Iron's list of commands as some sort of main catch-all fallback?

**Comment by chrisbutler** [comment]
@josephdburdick i think that's the general idea, and what currently happens in the code

the issue with ````mongo```` is that it creates an interactive shell, which is different than just passing back the output from a command

**Comment by josephdburdick** [comment]
Ohh, I understand the scale of complexity now. Thanks for clearing that up, @chrisbutler.

**Comment by jchan202** [comment]
I just started using iron-cli, and ran into the same issue.  So I installed MongoDB, and connected using:
mongo 127.0.0.1:3001/meteor

**Comment by jLouzado** [comment]
@jchan202 but it's not affecting your app's functionality right?

**Comment by jchan202** [comment]
@jLouzado I don't notice any 'side effect' so far.

**Comment by jLouzado** [comment]
just realized that the solution was listed several months months ago... `cd app/` and then run `meteor mongo`

**Comment by chrisbutler** [comment]
@seangrogg @shails @mitzip @therinken @connor11528 @jLouzado @jchan202 @josephdburdick this is fixed in 1.7.0 !

**Comment by kuba-04** [comment]
Do you mean this directory? /.meteor/local/build/programs/server/app ?
I can't find any other app/ folder. Anyway this one doesn't work for me, still have the same issue. 
Did it work for everyone here?
